spring:
  datasource:
    url       : jdbc:mysql://localhost:3306/prueba
    username  : root
    password  : 3442
  jpa:
    show-sql  : true 
    hibernate.ddl-auto: update
#    hibernate:#      naming:#        implicit-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect
         
     